steps:
  - label: "🔒 Enter gate"
    concurrency: 1
    concurrency_group: "test-gate/$BUILDKITE_BRANCH"

  - wait

  - label: "📤 Generate dynamic steps"
    key: gen
    command: ./generate-pipeline.sh

  - wait

  - label: "🔓 Exit gate"
    concurrency: 1
    concurrency_group: "test-gate/$BUILDKITE_BRANCH"
