steps:
  - label: ":pipeline: upload mini pipeline"
    command: |
      set -euo pipefail

      # Make sure the base ref exists locally.
      git fetch --prune origin "+refs/heads/*:refs/remotes/origin/*" --tags || true

      # Resolve the base (will use BUILDKITE_GIT_DIFF_BASE if you set it on the build).
      BASE="${BUILDKITE_GIT_DIFF_BASE:-origin/${BUILDKITE_PULL_REQUEST_BASE_BRANCH:-${BUILDKITE_PIPELINE_DEFAULT_BRANCH:-main}}}"
      echo "BASE=$BASE"

      # Generate the tiniest pipeline: one step that runs only if src/** changed.
      mkdir -p .buildkite
      cat > .buildkite/generated.yml <<'YAML'
      steps:
        - label: "Run if src/** changed"
          if_changed: ["src/**"]
          command: echo "src/** changed — running"
      YAML

      # Upload it with if_changed filtering against the chosen base.
      buildkite-agent pipeline upload \
        --config .buildkite/generated.yml \
        --apply-if-changed \
        --git-diff-base "$BASE"
