steps:
  - label: ":slot_machine: Flaky check (x3, any-pass)"
    key: flaky-parallel
    parallelism: 3
    soft_fail:
      - exit_status: 1        # failed shards don't fail the build
    command: |
      set -euo pipefail
      # Unique key per build to avoid stale metadata
      META_KEY="flaky_ok_${BUILDKITE_BUILD_ID}"

      # Deterministic: shard 0 passes, others fail (so you can prove it works)
      echo "Shard index: ${BUILDKITE_PARALLEL_JOB:-unknown}"
      if [[ "${BUILDKITE_PARALLEL_JOB:-9}" == "0" ]]; then
        echo "🎉 This shard is the winner"
        buildkite-agent meta-data set "$META_KEY" "true"
        exit 0
      else
        echo "💥 This shard fails on purpose"
        exit 1
      fi

  # Let the pipeline continue even if some shards failed
  - wait: ~
    continue_on_failure: true

  - label: ":white_check_mark: Gate (pass if any succeeded)"
    depends_on: flaky-parallel
    command: |
      set -euo pipefail
      META_KEY="flaky_ok_${BUILDKITE_BUILD_ID}"
      if [[ "$(buildkite-agent meta-data get "$META_KEY" || echo false)" == "true" ]]; then
        echo "✅ At least one parallel run passed."
        exit 0
      else
        echo "❌ All parallel runs failed."
        exit 1
      fi
