steps:
  - label: ":pipeline: Upload real pipeline (if_changed)"
    env:
      # For testing, hard-set a base (you’ll override this per build below).
      BUILDKITE_GIT_DIFF_BASE: "origin/main"
    command: |
      set -euxo pipefail
      git fetch --prune origin
      echo "--- Effective base"
      echo "BUILDKITE_GIT_DIFF_BASE=${BUILDKITE_GIT_DIFF_BASE:-unset}"

      # Upload the real pipeline; pass the base explicitly
      buildkite-agent pipeline upload \
        --apply-if-changed \
        --git-diff-base "${BUILDKITE_GIT_DIFF_BASE:-origin/${BUILDKITE_PULL_REQUEST_BASE_BRANCH:-${BUILDKITE_PIPELINE_DEFAULT_BRANCH:-main}}}"
