steps:
- command: echo "Enter gate"
  label: "🔒 Enter gate"
  concurrency: 1
  concurrency_group: "test-gate/main"

- wait: ~

- command: generate-pipeline.sh

- wait: ~

- command: echo "Exit gate"
  label: "🔓 Exit gate"
  concurrency: 1
  concurrency_group: "test-gate/main"

    
