steps:
  - label: "Test webhook access"
    command: |
      echo "Current commit: $BUILDKITE_COMMIT"
      echo "Before commit: ${BUILDKITE_COMMIT_BEFORE:-'Not set'}"
      
      # Show the difference if both are available
      if [ -n "${BUILDKITE_COMMIT_BEFORE:-}" ]; then
        echo "Commits changed:"
        git log --oneline ${BUILDKITE_COMMIT_BEFORE}..${BUILDKITE_COMMIT}
      fi
