steps:
  - label: ":package: Build if any code changed"
    command: |
      echo "Building application"
      echo "BUILDKITE_GIT_DIFF_BASE is set to: $BUILDKITE_GIT_DIFF_BASE"
    if_changed: "frontend/**;backend/**;shared/**"
    depends_on: setup
