steps:
  # Step 1: Always runs
  - label: ":white_check_mark: Step 1 - Always runs"
    key: "step-1"
    command: |
      echo "Step 1 is running"
      echo "This step always executes"

  # Step 2: Depends on existing step (should work normally)
  - label: ":arrow_right: Step 2 - Depends on existing step"
    key: "step-2"
    command: |
      echo "Step 2 is running"
      echo "This depends on step-1 which exists"
    depends_on:
      - step: "step-1"

  # Step 3: Depends on missing step with allow_missing: true (old behavior)
  - label: ":question: Step 3 - Missing dependency allowed"
    key: "step-3"
    command: |
      echo "Step 3 is running"
      echo "This depends on a missing step but allows it"
    depends_on:
      - step: "missing-step-1"
        allow_missing: true

  # Step 4: Depends on missing step with allow_missing: false (should fail)
  - label: ":x: Step 4 - Missing dependency fails"
    key: "step-4"
    command: |
      echo "Step 4 is running"
      echo "This should fail because missing-step-2 doesn't exist"
    depends_on:
      - step: "missing-step-2"
        allow_missing: false

  # Step 5: Test if_changed interaction (if available)
  - label: ":gear: Step 5 - Conditional step"
    key: "step-5"
    command: |
      echo "Step 5 is running"
      echo "This step runs conditionally based on file changes"
    if_changed: "**/*.md"  # Only runs if markdown files changed

  # Step 6: Depends on conditional step
  - label: ":link: Step 6 - Depends on conditional"
    key: "step-6"
    command: |
      echo "Step 6 is running"
      echo "This depends on step-5 which may or may not run"
    depends_on:
      - step: "step-5"
        allow_missing: true  # Allow if step-5 is skipped

  # Step 7: Multiple dependencies with mixed allow_missing
  - label: ":building_construction: Step 7 - Mixed dependencies"
    key: "step-7"
    command: |
      echo "Step 7 is running"
      echo "This has multiple dependencies with different allow_missing settings"
    depends_on:
      - step: "step-2"  # exists
      - step: "missing-step-3"
        allow_missing: true  # missing but allowed
      - step: "missing-step-4"
        allow_missing: false  # missing and should fail
