steps:
  - label: ":pipeline: Upload conditional steps"
    command: |
      set -euo pipefail

      # Make sure the base ref exists locally (useful on fresh/shallow clones)
      git fetch --prune origin "+refs/heads/*:refs/remotes/origin/*" --tags || true

      # Resolve the base: BUILDKITE_GIT_DIFF_BASE (if set) -> PR base -> default branch -> main
      BASE="${BUILDKITE_GIT_DIFF_BASE:-origin/${BUILDKITE_PULL_REQUEST_BASE_BRANCH:-${BUILDKITE_PIPELINE_DEFAULT_BRANCH:-main}}}"
      echo "Using diff base: $BASE"
      git rev-parse "$BASE" >/dev/null

      # Upload the second YAML with if_changed filtering against BASE
      buildkite-agent pipeline upload .buildkite/conditional.yml \
        --apply-if-changed \
        --git-diff-base "$BASE"
