steps:
  - label: test-1
    key: main
    command: sleep 100
    priority: 10
    timeout_in_minutes: 30
  - label: test-2
    command: exit 1
    timeout_in_minutes: 30
    depends_on: main
    notify:
    - github_commit_status:
        context: buildkite/test-2
      if: step.state == 'waiting_for_dependencies' || step.state == 'running' || step.state
        == 'finished'

